java -jar NLR-Annotator-v2.1b.jar -t 4 -i HP301.pseudomolecules-v1.fasta.mod -x mot.txt -y store.txt -o HP301.pseudomolecules-v1.out -b HP301.pseudomolecules-v1.bed
java -jar NLR-Annotator-v2.1b.jar -t 4 -i Il14H.pseudomolecules-v2.fasta.mod -x mot.txt -y store.txt -o Il14H.pseudomolecules-v2.out -b Il14H.pseudomolecules-v2.bed
java -jar NLR-Annotator-v2.1b.jar -t 4 -i Ki11.pseudomolecules-v1.fasta.mod -x mot.txt -y store.txt -o Ki11.pseudomolecules-v1.out -b Ki11.pseudomolecules-v1.bed
java -jar NLR-Annotator-v2.1b.jar -t 4 -i Ki3.pseudomolecules-v1.fasta.mod -x mot.txt -y store.txt -o Ki3.pseudomolecules-v1.out -b Ki3.pseudomolecules-v1.bed
java -jar NLR-Annotator-v2.1b.jar -t 4 -i Ky21.pseudomolecules-v1.fasta.mod -x mot.txt -y store.txt -o Ky21.pseudomolecules-v1.out -b Ky21.pseudomolecules-v1.bed
java -jar NLR-Annotator-v2.1b.jar -t 4 -i M162W.pseudomolecules-v1.fasta.mod -x mot.txt -y store.txt -o M162W.pseudomolecules-v1.out -b M162W.pseudomolecules-v1.bed
java -jar NLR-Annotator-v2.1b.jar -t 4 -i M37W.pseudomolecules-v1.fasta.mod -x mot.txt -y store.txt -o M37W.pseudomolecules-v1.out -b M37W.pseudomolecules-v1.bed
java -jar NLR-Annotator-v2.1b.jar -t 4 -i Mo18W.pseudomolecules-v1.fasta.mod -x mot.txt -y store.txt -o Mo18W.pseudomolecules-v1.out -b Mo18W.pseudomolecules-v1.bed
java -jar NLR-Annotator-v2.1b.jar -t 4 -i Ms71.pseudomolecules-v1.fasta.mod -x mot.txt -y store.txt -o Ms71.pseudomolecules-v1.out -b Ms71.pseudomolecules-v1.bed
java -jar NLR-Annotator-v2.1b.jar -t 4 -i NC350.pseudomolecules-v1.fasta.mod -x mot.txt -y store.txt -o NC350.pseudomolecules-v1.out -b NC350.pseudomolecules-v1.bed
java -jar NLR-Annotator-v2.1b.jar -t 4 -i B73.PLATINUM.pseudomolecules-v1.fasta.mod -x mot.txt -y store.txt -o B73.PLATINUM.pseudomolecules-v1.out -b B73.PLATINUM.pseudomolecules-v1.bed
java -jar NLR-Annotator-v2.1b.jar -t 4 -i NC358.pseudomolecules-v1.fasta.mod -x mot.txt -y store.txt -o NC358.pseudomolecules-v1.out -b NC358.pseudomolecules-v1.bed
java -jar NLR-Annotator-v2.1b.jar -t 4 -i Oh43.pseudomolecules-v1.fasta.mod -x mot.txt -y store.txt -o Oh43.pseudomolecules-v1.out -b Oh43.pseudomolecules-v1.bed
java -jar NLR-Annotator-v2.1b.jar -t 4 -i Oh7b.pseudomolecules-v2.fasta.mod -x mot.txt -y store.txt -o Oh7b.pseudomolecules-v2.out -b Oh7b.pseudomolecules-v2.bed
java -jar NLR-Annotator-v2.1b.jar -t 4 -i P39.pseudomolecules-v2.fasta.mod -x mot.txt -y store.txt -o P39.pseudomolecules-v2.out -b P39.pseudomolecules-v2.bed
java -jar NLR-Annotator-v2.1b.jar -t 4 -i Tx303.pseudomolecules-v1.fasta.mod -x mot.txt -y store.txt -o Tx303.pseudomolecules-v1.out -b Tx303.pseudomolecules-v1.bed
java -jar NLR-Annotator-v2.1b.jar -t 4 -i Tzi8.pseudomolecules-v1.fasta.mod -x mot.txt -y store.txt -o Tzi8.pseudomolecules-v1.out -b Tzi8.pseudomolecules-v1.bed
java -jar NLR-Annotator-v2.1b.jar -t 4 -i B97.pseudomolecules-v1.fasta.mod -x mot.txt -y store.txt -o B97.pseudomolecules-v1.out -b B97.pseudomolecules-v1.bed
java -jar NLR-Annotator-v2.1b.jar -t 4 -i CML103.pseudomolecules-v1.fasta.mod -x mot.txt -y store.txt -o CML103.pseudomolecules-v1.out -b CML103.pseudomolecules-v1.bed
java -jar NLR-Annotator-v2.1b.jar -t 4 -i CML228.pseudomolecules-v1.fasta.mod -x mot.txt -y store.txt -o CML228.pseudomolecules-v1.out -b CML228.pseudomolecules-v1.bed
java -jar NLR-Annotator-v2.1b.jar -t 4 -i CML247.pseudomolecules-v1.fasta.mod -x mot.txt -y store.txt -o CML247.pseudomolecules-v1.out -b CML247.pseudomolecules-v1.bed
java -jar NLR-Annotator-v2.1b.jar -t 4 -i CML322.pseudomolecules-v2.fasta.mod -x mot.txt -y store.txt -o CML322.pseudomolecules-v2.out -b CML322.pseudomolecules-v2.bed
java -jar NLR-Annotator-v2.1b.jar -t 4 -i CML333.pseudomolecules-v1.fasta.mod -x mot.txt -y store.txt -o CML333.pseudomolecules-v1.out -b CML333.pseudomolecules-v1.bed
java -jar NLR-Annotator-v2.1b.jar -t 4 -i CML52.pseudomolecules-v2.1.fasta.mod -x mot.txt -y store.txt -o CML52.pseudomolecules-v2.1.out -b CML52.pseudomolecules-v2.1.bed
java -jar NLR-Annotator-v2.1b.jar -t 4 -i CML69.pseudomolecules-v1.fasta.mod -x mot.txt -y store.txt -o CML69.pseudomolecules-v1.out -b CML69.pseudomolecules-v1.bed
